review project
JayKowski/new-york-times pull request #1
Opened 2019-08-28 22:24 UTC by JayKowski

project complete, ready for review

2019-08-28 23:21 UTC, stratospherique reviewed
### Pull request under the review by Ahmed Mahfoudh TSE

2019-08-28 23:38 UTC, stratospherique requested changes
### Splendid work guys :clap: :clap: . However, some changes that prevents your project's approval needs to be made:

##### Footer

* [ ] It should have a fixed position (it sticks to the bottom part of the screen).

- You could consider a fixed footer like the image below but with less height
![image](https://user-images.githubusercontent.com/26124023/63899112-8a894a80-c9f3-11e9-9aac-69f1b1b0f23c.png)

#### Implementation details

* [ ] Elements should be aligned with [float](https://css-tricks.com/all-about-floats/). For the `aside` section you are using absolute positioning :no_entry_sign: . Use floats :eyeglasses:

#### General notes:

* [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.


### That's it :relieved: . When finsihed, kindly resubmit another code review request :pray: . Keep up the good work :muscle: :muscle: .

2019-08-28 23:38 UTC, stratospherique commented on css/main.css
> +  /* width: 80%; */
https://github.com/JayKowski/new-york-times/blob/ffcb4f462975829b071e2214a98b2c7f49f3fd18/css/main.css#L828-L830

- Delete commented code

2019-08-29 19:38 UTC, uche-inyama approved these changes
### Hello team! nice work. Job well-done. :raised_hands: :rocket: 
#### Go ahead and merge to master branch :smile: 
- [x] Your project doesn't have linter checks, please, ensure your setting are implemented the correct way.
### Keep up the good work :+1:

2019-08-29 20:35 UTC, merged